---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: içerik
- type: directory
  path: _posts
  label: Yazılar
  create: all
  match: "**/*"
  templates:
  - posts
- type: jekyll-pages
  label: Sayfalar
  create: all
  templates:
  - landing-page
  - default
- type: directory
  path: _ekip
  label: Ekip
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _affilates
  label: İş Ortakları
  create: all
  match: "*"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: İletişim
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
